'use client';
import { useEffect, useMemo, useState } from 'react';
import { BriefcaseBusiness, Plus, Search, Users } from 'lucide-react';
import api, { apiErrorMessage } from '@/lib/api';
import { useAuth } from '@/lib/auth-context';
import { PageHeader } from '@/components/ui/PageHeader';
import { Button } from '@/components/ui/Button';

interface Employee { id:string; user_id:string; employee_id:string; department:string; designation:string }
interface User { id:string; email:string; full_name?:string|null }
export default function HRPage(){
 const {can}=useAuth(); const [employees,setEmployees]=useState<Employee[]>([]); const [users,setUsers]=useState<User[]>([]); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(''); const [success,setSuccess]=useState(''); const [search,setSearch]=useState('');
 const [form,setForm]=useState({user_id:'',employee_id:'',department:'',designation:''}); const canCreate=can('hr.employee.create');
 const load=async()=>{setLoading(true);setError('');try{const requests:[Promise<any>,Promise<any>|null]=[api.get('/hr/employees'),canCreate?api.get('/users/'):null];const employeeRes=await requests[0];setEmployees(employeeRes.data);if(requests[1])setUsers((await requests[1]).data);}catch(e){setError(apiErrorMessage(e,'Unable to load HR information.'));}finally{setLoading(false);}};
 useEffect(()=>{void load();},[canCreate]);
 const visible=useMemo(()=>{const q=search.trim().toLowerCase();return !q?employees:employees.filter(e=>`${e.employee_id} ${e.department} ${e.designation}`.toLowerCase().includes(q));},[employees,search]);
 const departments=new Set(employees.map(e=>e.department).filter(Boolean)).size;
 const createEmployee=async()=>{setError('');setSuccess('');if(!form.user_id||!form.employee_id.trim()||!form.department.trim()||!form.designation.trim())return setError('User, employee ID, department and designation are required.');setSaving(true);try{await api.post('/hr/employees',{...form,employee_id:form.employee_id.trim(),department:form.department.trim(),designation:form.designation.trim()});setForm({user_id:'',employee_id:'',department:'',designation:''});setSuccess('Employee created successfully.');await load();}catch(e){setError(apiErrorMessage(e,'Unable to create employee.'));}finally{setSaving(false);}};
 return <div className="space-y-6"><PageHeader title="HR & Payroll" description="Manage employees, departments and workforce records from one secure workspace."/>
 <div className="grid gap-4 sm:grid-cols-3"><Stat label="Employees" value={employees.length} icon={<Users size={20}/>}/><Stat label="Departments" value={departments} icon={<BriefcaseBusiness size={20}/>}/><Stat label="Visible Records" value={visible.length} icon={<Search size={20}/>}/></div>
 {error&&<div className="rounded-md border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}{success&&<div className="rounded-md border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700">{success}</div>}
 {canCreate&&<div className="card p-5"><h2 className="font-semibold text-slate-900">Add Employee</h2><p className="mb-4 text-sm text-slate-500">Link an existing ERP user to an employee record.</p><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><select className="input" value={form.user_id} onChange={e=>setForm({...form,user_id:e.target.value})}><option value="">Select user</option>{users.map(u=><option key={u.id} value={u.id}>{u.full_name||u.email}</option>)}</select><input className="input" value={form.employee_id} onChange={e=>setForm({...form,employee_id:e.target.value})} placeholder="Employee ID"/><input className="input" value={form.department} onChange={e=>setForm({...form,department:e.target.value})} placeholder="Department"/><input className="input" value={form.designation} onChange={e=>setForm({...form,designation:e.target.value})} placeholder="Designation"/></div><div className="mt-4 flex justify-end"><Button onClick={createEmployee} disabled={saving}><Plus size={17}/>{saving?'Creating...':'Create Employee'}</Button></div></div>}
 <div><div className="mb-4 flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h2 className="font-semibold">Employee Directory</h2><p className="text-sm text-slate-500">Search by ID, department or designation.</p></div><div className="relative sm:w-80"><Search size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input className="input pl-9" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search employees..."/></div></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Employee ID</th><th>Department</th><th>Designation</th></tr></thead><tbody>{loading?<tr><td colSpan={3} className="py-10 text-center">Loading employees...</td></tr>:visible.length===0?<tr><td colSpan={3} className="py-12 text-center text-slate-500">No employee records found.</td></tr>:visible.map(e=><tr key={e.id}><td className="font-medium text-slate-900">{e.employee_id}</td><td>{e.department}</td><td>{e.designation}</td></tr>)}</tbody></table></div></div></div>;
}
function Stat({label,value,icon}:{label:string;value:number;icon:React.ReactNode}){return <div className="card flex items-center justify-between p-5"><div><p className="text-sm text-slate-500">{label}</p><p className="mt-1 text-2xl font-bold">{value}</p></div><div className="rounded-lg bg-slate-100 p-3 text-slate-600">{icon}</div></div>}
